server:
  port: 8888
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: ${DB_SCHEMA}
        #format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # show-sql: true
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: ${DB_URL}
springdoc:
  api-docs:
    path= /docs:
values:
  security:
    hash: "elmonotiti"
    expitarionToken: 3
